// hillis steele inclusive float3 max scan

#define BLOCK_SZ 64

RWStructuredBuffer<float3> cb_in;
StructuredBuffer<float3> cb_prev;

uniform uint _len;
uniform uint _offset;

#pragma kernel HillisSteeleFloat3MaxScan
[numthreads(BLOCK_SZ, 1, 1)]
void HillisSteeleFloat3MaxScan(uint DTid : SV_DISPATCHTHREADID)
{
  if (DTid >= _len) return;

  int sumIdx = DTid - _offset;
  if (sumIdx >= 0) cb_in[DTid] = max(cb_prev[sumIdx], cb_in[DTid]);
}